config/routes.rb
Rails.application.routes.draw do
  get 'tweets/new'

  get 'tweets/create'
  resources :tweets, only: [:new, :create]
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'  }
devise_scope :user do
  get 'sign_up_foundation', to: 'devise/registrations#new'
end

  resources :campaigns

  get "complete_profile", to: 'complete_profile#index'
  patch "complete_profile", to: 'complete_profile#save'
  get '/', to: 'defaults#index'
  get '/prueba', to: 'defaults#prueba'
  

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
  end

  def create
  	current_user.tweet(twitter_params[:message])
  end

  def twitter_params
    params.require(:tweet).permit(:message)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/create.html.erb
<h1>Success!</h1>
<p>Your tweet has been sent!</p>
<%= link_to "Would you like to send another?", new_tweet_path %>

app/views/tweets/new.html.erb
<!--<div id ="botonformulariotweet">
<p>
  <%= form_for :tweet, url: tweets_path, method: :post do |f| %>
    <%= f.text_field :message %>
    <%= f.submit "Send Tweet" %>
  <% end %>
</p>
<div>-->


   

   <section id="features" class="features section">
        <div class="container text-center">
            <h2 class="title">Features</h2>
<p>
  <%= form_for :tweet, url: tweets_path, method: :post do |f| %>
    <%= f.text_field :message %>
    <%= f.submit "Send Tweet" %>
  <% end %>
</p>            




        </div><!--//container-->
    </section><!--//features-->