config/routes.rb
Rails.application.routes.draw do
  get 'tweets/new'

  get 'tweets/create'
  resources :tweets, only: [:new, :create]
  devise_for :users, :controllers => { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations'  }
devise_scope :user do
  get 'sign_up_foundation', to: 'devise/registrations#new'
end

  resources :campaigns

  get "complete_profile", to: 'complete_profile#index'
  patch "complete_profile", to: 'complete_profile#save'
  get '/', to: 'defaults#index'
  get '/prueba', to: 'defaults#prueba'
  

  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  

end

app/views/shared/_navbar.html.erb
<!--<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container"> 
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a target="_blank" href="#" class="navbar-brand">My sApp.</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="../">Inicio</a></li>
                <li class="active"><a >Inspirado en este ejemplo</a></li>
                 <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">DropDown
                    <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Link 2</a></li>
                    </ul>
                 </li>              
             </ul>
             <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span> 
                        <strong><%= @user.name%></strong>
                        <strong><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                            
                                            <img src=<%=@user.photo_url%> class="icon-size" style="width:120%;">
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p ><strong><%= @user.username%></strong></p>
                                        <p class="text-left small"><%= @user.email%></p>
                                        <p>
                                            <%= link_to 'Actualizar datos', complete_profile_path, :class => "btn btn-primary btn-block"%>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p>
                                            
                                            <%= link_to 'Cerrar Sesión', destroy_user_session_path, :method => :delete , :class => "btn btn-danger btn-block" %>

                                        </p>

                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
            <% else %>
            <ul class="nav navbar-nav navbar-right">
                <li>
            <%= link_to "Registrarse Fundación", new_contact_path, :class => "btn btn-default" %>
            
                </li>

                <li>
            <%= link_to "Registrarse", new_user_registration_path, :class => "btn btn-default" %>
            
                </li>
                <li>
                <%= link_to "Iniciar sesión", new_user_session_path, :class => "btn btn-default" %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</div>-->